### ISSUE TITLE
Break and return a non-zero exit status if any sub-command returns a non-zero exit status?

### ISSUE THREAD

**Issue by darraghbuckley** [kamataryo/monorepo#24]
Should the return of a non-zero exit status from any `local_command_str`[0] cause the loop to break and return a non-zero exit status?

The use-case is for things like running `monorepo rake test` where the expectation might be that if any gem's tests fail that a non-zero exit status would be returned. (The current behavior is to return a zero exit status regardless of failure.) It would make configuration of continuous integration services easier.

I'm happy to write a Pull Request if you think this is reasonable behavior.

0. https://github.com/kamataryo/monorepo/blob/master/lib/commands/exec.rb#L34

**Comment by kamataryo** [comment]
Hi, @darraghbuckley, thank you for the feedback!
Yes, I think it's reasonable and one of the most important features. Pull Requests are always welcome. I appreciate your offer!

**Comment by kamataryo** [comment]
@darraghbuckley Just a notification for newly released RubyGem monorepo@0.2.0!
https://rubygems.org/gems/monorepo/versions/0.2.0

**Comment by darraghbuckley** [comment]
@kamataryo Thanks, thanks!
